---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

ContactPageController:
  from_email: 'website@tairawhitiinvestments.nz'
  from_name: 'Tairāwhiti Investments'
  recipient_email: 'info@tairawhitiinvestments.nz'
  bcc_email: 'nick@nfx.nz'
